spring.application.name=ManageNotes
logging.level.com.university.ManageNotes.security=DEBUG

# Configuration du serveur
server.port=3030

# database configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/managerNotes
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}



# Configuration JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
app.jwtSecret=R2RThdHu3OKhHvJ3QgUnkQsVv8Af+Jsw9A9+1oSx6nE=
app.jwtExpirationMs=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email Configuration (if needed)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OpenAPI Documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security Configuration
spring.security.enabled=true

spring.config.import=optional:file:.env[.properties]
