package com.university.ManageNotes.service;

import com.university.ManageNotes.dto.Request.ReportRequest;
import com.university.ManageNotes.dto.Response.ReportResponse;
import com.university.ManageNotes.model.Grades;
import com.university.ManageNotes.model.Students;
import com.university.ManageNotes.model.Users;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

@Service
public class ReportService {

    @Autowired
    private AuthService authService;

    @Autowired
    private GradeService gradeService;

    public byte[] generatePDFReport(Students student, List<Grades> grades, String reportTitle) throws IOException {
        try {
            // Get current user for audit purposes
            Users currentUser = authService.getCurrentUser();

            // Create PDF document
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            // Simulate PDF generation (replace with actual PDF library like iText or Apache PDFBox)
            String pdfContent = generatePDFContent(student, grades, reportTitle, currentUser);
            outputStream.write(pdfContent.getBytes());

            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new IOException("Error generating PDF report: " + e.getMessage());
        }
    }

    private String generatePDFContent(Students student, List<Grades> grades, String reportTitle, Users currentUser) {
        StringBuilder content = new StringBuilder();
        content.append("=== ").append(reportTitle).append(" ===\n");
        content.append("Student: ").append(student.getFirstName()).append(" ").append(student.getLastName()).append("\n");
        content.append("Generated by: ").append(currentUser.getFirstName()).append(" ").append(currentUser.getLastName()).append("\n\n");

        content.append("GRADES:\n");
        for (Grades grade : grades) {
            content.append("Subject: ").append(grade.getSubject().getName()).append("\n");
            content.append("Value: ").append(grade.getValue()).append("\n");
            content.append("Coefficient: ").append(grade.getCoefficient()).append("\n");
            content.append("Type: ").append(grade.getGradeType().name()).append("\n");
            content.append("Semester: ").append(grade.getSemesters().getName()).append("\n");
            content.append("Comments: ").append(grade.getComments()).append("\n");
            content.append("------------------------\n");
        }

        return content.toString();
    }

    public ReportResponse generateStudentReport(Long studentId, ReportRequest reportRequest) {
        try {
            // Logic to generate student report
            ReportResponse response = new ReportResponse();
            response.setReportType("STUDENT_GRADES");
            response.setStudentId(studentId);
            response.setSuccess(true);
            response.setMessage("Report generated successfully");

            return response;
        } catch (Exception e) {
            ReportResponse response = new ReportResponse();
            response.setSuccess(false);
            response.setMessage("Failed to generate report: " + e.getMessage());
            return response;
        }
    }

    public ReportResponse generateClassReport(Long classId, ReportRequest reportRequest) {
        try {
            // Logic to generate class report
            ReportResponse response = new ReportResponse();
            response.setReportType("CLASS_GRADES");
            response.setClassId(classId);
            response.setSuccess(true);
            response.setMessage("Class report generated successfully");

            return response;
        } catch (Exception e) {
            ReportResponse response = new ReportResponse();
            response.setSuccess(false);
            response.setMessage("Failed to generate class report: " + e.getMessage());
            return response;
        }
    }

    public ReportResponse generateSubjectReport(Long subjectId, ReportRequest reportRequest) {
        try {
            // Logic to generate subject report
            ReportResponse response = new ReportResponse();
            response.setReportType("SUBJECT_GRADES");
            response.setSubjectId(subjectId);
            response.setSuccess(true);
            response.setMessage("Subject report generated successfully");

            return response;
        } catch (Exception e) {
            ReportResponse response = new ReportResponse();
            response.setSuccess(false);
            response.setMessage("Failed to generate subject report: " + e.getMessage());
            return response;
        }
    }

    public byte[] exportToExcel(List<Grades> grades) throws IOException {
        // Simulate Excel export
        StringBuilder csvContent = new StringBuilder();
        csvContent.append("Student,Subject,Grade,Coefficient,Type,Semester\n");

        for (Grades grade : grades) {
            csvContent.append(grade.getStudent().getFirstName()).append(" ").append(grade.getStudent().getLastName()).append(",");
            csvContent.append(grade.getSubject().getName()).append(",");
            csvContent.append(grade.getValue()).append(",");
            csvContent.append(grade.getCoefficient()).append(",");
            csvContent.append(grade.getGradeType().name()).append(",");
            csvContent.append(grade.getSemesters().getName()).append("\n");
        }

        return csvContent.toString().getBytes();
    }
}
